### ISSUE TITLE
.sls files are also SaltStack states (YAML), not Scheme

### ISSUE THREAD

**Issue by stevage** [github/linguist#960]
Plenty of sample material here if needed:

https://github.com/saltstack/salt-states

**Comment by pchaigno** [comment]
@stevage @jandd This issue should be fixed.

@stevage The statistics of your repository are currently not up-to-date. They will update if you make a new commit. Alternatively you can contact support@github.com to ask them to update it.

**Comment by stevage** [comment]
Thanks. (Whoa, that was a blast from the past...)

**Comment by pchaigno** [comment]
@stevage Yep, sorry it took so long...

**Comment by DavidJFelix** [comment]
This is still an issue.
Examples:

-  https://github.com/saltstack/salt-winrepo
-  https://github.com/saltstack/salt-jenkins/search?l=scheme

**Comment by pchaigno** [comment]
@DavidJFelix These repositories are indeed not up-to-date. The new results are much better:
```
~/salt-jenkins$ linguist --breakdown
77.91%  ApacheConf
20.35%  Python
1.51%   HTML
0.23%   Shell

Python:
_grains/external_ip.py
_grains/python_executable.py
_modules/runtests.py
_states/runtests.py

ApacheConf:
apache/httpd.conf

Shell:
halite/master/files/install_node_npm.sh

HTML:
halite/settings.jinja
```

```
~/salt-winrepo$ linguist --breakdown
100.00% Scheme

Scheme:
gimp.sls
gpg4win-light.sls
npp.sls
openoffice.sls
truecrypt.sls
```

salt-winrepo still has a few mis-detected files. If the project was under an OSS license I could add these files to our samples but even so, results will never be perfect :/

**Comment by DavidJFelix** [comment]
@pchaigno I think a big factor in the visibility of this bug is that salt is not represented in the percentage "color graph" but scheme is. Even if 90% of the the files are identified as salt and 5% are scheme, at least half of the bar will show up as scheme because the salt files are suppressed from the graph.

puppet has it's own color (slightly different from ruby's red). I think it might be appropriate to affiliate salt with python or jinja templates (which in many of the cases above are actually detected as django templates) and display it in the bar.

**Comment by pchaigno** [comment]
Salt state files are not counted in the statistics because Linguist considers them as `data`. Only `programming` and `markup` languages are part of the language bar.

**Comment by DavidJFelix** [comment]
hmm. I mean, salt is more than just yaml data. A `sls` file is technically a jinja2 template of yaml that's parsed and compiled before it becomes data. Consider the following: https://github.com/saltstack-formulas/apache-formula/blob/master/apache/modules.sls

There is no switch to tell salt to analyze this with jinja rather than directly import it - all salt files are parsed with jinja2 a templating engine. What is the qualification for markup over data? I mean, surely yaml rides that line already?

**Comment by pchaigno** [comment]
Good point, I think you should open a separate issue to discuss this.

**Comment by DavidJFelix** [comment]
Alright, will do. Sidenote, @UtahDave has clarified in https://github.com/saltstack/salt-winrepo/issues/192 that the code is Apache 2.0 and will be updating the repo shortly. 

Thanks @pchaigno

**Comment by UtahDave** [comment]
The license file on https://github.com/saltstack/salt-winrepo has been added to reflect our intention of those files being licensed under the Apache 2.0 license.  My apologies for the oversight.

For reference: https://github.com/saltstack/salt-winrepo/commit/47995fb2c18346a6f4e0ecc9912e3003ab7aa912

**Comment by pchaigno** [comment]
@UtahDave Thanks! I opened a pull request at #2311 to use files from your repository as samples for Linguist's Bayesian classifier.
